### ISSUE TITLE
Request Github remove "fork" status from repository

### ISSUE THREAD

**Issue by alerque** [vim-pandoc/vim-markdownfootnotes#16]
This repository is marked as a "fork" of the vim script that got things started. This makes a little bit of sense, but I think on balance the cons now outweigh the pros of this status.

* The original plugin is 100% dormant.
* The original is not the canonical location even for the original plugin, it is a a mirror of something else.
* This plugin has _substantially_ different functionality from the original.
* This repository is the canonical repository against which contributors submit contributions.
* Contributors are not getting credited properly because Github doesn't count contributions to forks.
* Opening pull requests is confusing  because they default to being against the vim-scripts repo instead of this one.
* We have even rebased the two commits from the original parent project because they had invalid timestamps (#5).

Github states:

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact) or GitHub Premium Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

I suggest that it is time to open a support request to remove the "forked from" status making this the canonical project, and that all other forks should be reallocated to be part of _this_ network.

**Comment by fmoralesc** [comment]
I have contacted Github support, and requested the detachment of this repo and vim-pandoc's.

**Comment by fmoralesc** [comment]
Our request to detach the repos has been accepted, they should be detached within the hour ;)
