### ISSUE TITLE
Automatically set footnote counter

### ISSUE THREAD

**Issue by alerque** [vim-pandoc/vim-markdownfootnotes#3]
Setting the footnote counter manually when opening a file is a needless piece of work that could be done automatically. There seem to be at least two, maybe three, implementations of this in forks that have not been submitted as PRs yet. This is a generally useful feature that should be upstreamed.

It could possibly be put behind an options flag, but I struggle to see who that would help. One could always override in anyway so what's the harm in starting  everybody off with an educated guess by default?

**Comment by fmoralesc** [comment]
I agree. Convention and sane defaults are more important than customizability.
