### ISSUE TITLE
The inserted footnote number may be the same with existing footnote mark

### ISSUE THREAD

**Issue by jdhao** [vim-pandoc/vim-markdownfootnotes#9]
If you open a markdown file which has some footnote in it and insert footnote before existing footnotes,  this plugin will insert a footnote mark number which already exists. 

It would be great if the footnote mark is generated randomly from some predefined characters  (e.g, alphanumeric characters) and has length two or three (two or three is enough since the combination of characters is already huge). In this way, the probability of footnote mark collision will be reduced greatly.

**Comment by alerque** [comment]
The old way of doing this was to run `FootnoteNumber x` to set the starting number manually whenever you started work on a new file. As noted in issue #3 making the plugin auto-detect what the next available footnote number is is quite desirable, and pull request #7 has an (currently untested) implementation of this in the works. As I understand it that feature should cover your use case as well ensuring no footnote number clobbering. Feel free to comment if not!

**Comment by alerque** [comment]
@jdhao I just merged that PR, so the auto numbering is active now if you update your plugin. Let us know if that solves your use case as well.

**Comment by jdhao** [comment]
I have updated the plugin. It works great. Thanks~
